# Generated by Django 3.1.4 on 2021-01-05 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='client',
        ),
        migrations.AddField(
            model_name='rider',
            name='branch',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='delivery.branch'),
            preserve_default=False,
        ),
    ]
