# Generated by Django 3.1.4 on 2021-01-04 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riderlocation',
            name='id',
        ),
        migrations.AlterField(
            model_name='riderlocation',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='delivery.request'),
        ),
    ]
