# Generated by Django 3.1.4 on 2020-12-29 21:23

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_auto_20201230_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='delivery_location',
            field=django_mysql.models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='request',
            name='pickup_location',
            field=django_mysql.models.JSONField(default=dict),
        ),
    ]
