# Generated by Django 3.1.4 on 2021-01-11 10:09

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_riderlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderlocation',
            name='current_location',
            field=django_mysql.models.ListTextField(models.CharField(max_length=60), size=None),
        ),
    ]
